config/routes.rb
Rails.application.routes.draw do

  get    '/vote',    to: 'votelot#new'

  get    '/idea',    to: 'bandnames#new'
  post   '/idea',    to: 'bandnames#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/home',    to: 'main#home'
  get    '/signup',  to: 'users#new'

  root   'main#home'

  resources :users
  resources :bandnames,   only: [:new, :create, :show] do
    member do
      put "like", to: "bandnames#vote"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bandname.rb
class Bandname < ApplicationRecord
    acts_as_votable
    belongs_to :user
    validates :user_id, presence: true
    validates :name, presence: true, length: { maximum: 50 },
        uniqueness: { case_sensitive: false }

    def rating
        find_votes_for().average(:vote_weight)
    end

    def blank_stars
        5 - rating.to_i
    end
end

app/models/user.rb
class User < ApplicationRecord
    acts_as_voter
    has_many :bandnames
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence:   true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/bandnames_controller.rb
class BandnamesController < ApplicationController

  def show
    @bandname = Bandname.find(params[:id])
  end

  def new
    @bandname = Bandname.new
  end

  def create
    @bandname = current_user.bandnames.build(bandname_params)
    if @bandname.save
      flash[:success] = "New band name logged"
      redirect_to @bandname
    else
      render 'new'
    end
  end

  def vote 
    @bandname = Bandname.find(params[:id])
    @bandname.upvote_by current_user, {vote_weight: params[:rank]}
    redirect_back(fallback_location: root_url)
  end  
  
  private

    def bandname_params
      params.require(:bandname).permit(:name)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  require 'will_paginate/array' 
  
  def home
    @bandnames = Bandname.order(:cached_weighted_average => :desc).paginate(page: params[:page])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    # Users without password digest were created before passwords were added to the database
    if user && (!user.password_digest || user.authenticate(params[:session][:password]))
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @bandnames = @user.bandnames.paginate(page: params[:page])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Bandnamit!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/votelot_controller.rb
class VotelotController < ApplicationController
  def new
    @lot = Bandname.order(:cached_votes_total).limit(5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bandnames_helper.rb
module BandnamesHelper
    def current_user_vote(bandname)
        v = bandname.find_votes_for({ voter_id: current_user.id })
        v.size > 0? v.first.vote_weight: 0
    end

    def current_user_blanks(bandname)
        5 - current_user_vote(bandname)
    end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns true if the given user is the current user
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default)
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/helpers/votelot_helper.rb
module VotelotHelper
end

app/views/bandnames/_bandname.html.erb
<tr>
  <th scope="row">
    <%= link_to bandname.name, bandname %> 
  </th>
  <td>
    <%= number_with_precision(bandname.cached_weighted_average, precision: 2) %>
    <% bandname.rating.to_i.times do  %>
      <%= render 'layouts/voteup' %>
    <% end %>
    <% bandname.blank_stars.times do %>
      <%= render 'layouts/votedn' %>
    <% end %>
    (<%= bandname.cached_votes_total %>)
  </td>
</tr>

app/views/bandnames/new.html.erb
<% provide(:title, 'Band name idea') %>
<h1>New Band Name</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@bandname, url: idea_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Band name" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bandnames/show.html.erb
<% provide(:title, @bandname.name) %>
<h1>
  <%= @bandname.name %>
</h1>
<p>Vote by clicking the stars.</p>
<ul>
  <li>Created by <%= User.find(@bandname.user_id).name %></li>
  <% if logged_in? %>
    <li>Your vote: <%= render partial: 'layouts/vote', locals: {bandname: @bandname} %></li>
  <% end %>
</ul>
<p><%= link_to "Home", root_path, :class => "btn btn-primary" %></p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Bandnamit by Mat Kramer
  </small>
  <nav>
    <ul>
      <li><a href="https://github.com/mek363/bandnames/issues">Feedback</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <div class='navbar-header'>
        <%= link_to "Bandnamit", root_path, id: "logo" %>
      </div>
      <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <% if logged_in? %>
                <%= @current_user.name %> <b class="caret"></b>
              <% else %>
                Bandnamer <b class="caret"></b>
              <% end %>
            </a>
            <ul class="dropdown-menu">
            <% if logged_in? %>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Users", users_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
              <li><%= link_to "Sign up", signup_path %></li>
            <% end %>
            </ul>
          </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_vote.html.erb
      <!-- 1 star -->
      <%= link_to like_bandname_path(bandname, :rank => 1), method: :put do %>
        <% if current_user_vote(bandname) > 0 %>
          <%= render 'layouts/voteup' %>
        <% else %>
          <%= render 'layouts/votedn' %>
        <% end %>
      <% end %>
      <!-- 2 star -->
      <%= link_to like_bandname_path(bandname, :rank => 2), method: :put do %>
        <% if current_user_vote(bandname) > 1 %>
          <%= render 'layouts/voteup' %>
        <% else %>
          <%= render 'layouts/votedn' %>
        <% end %>
      <% end %>
      <!-- 3 star -->
      <%= link_to like_bandname_path(bandname, :rank => 3), method: :put do %>
        <% if current_user_vote(bandname) > 2 %>
          <%= render 'layouts/voteup' %>
        <% else %>
          <%= render 'layouts/votedn' %>
        <% end %>
      <% end %>
      <!-- 4 star -->
      <%= link_to like_bandname_path(bandname, :rank => 4), method: :put do %>
        <% if current_user_vote(bandname) > 3 %>
          <%= render 'layouts/voteup' %>
        <% else %>
          <%= render 'layouts/votedn' %>
        <% end %>
      <% end %>
      <!-- 5 star -->
      <%= link_to like_bandname_path(bandname, :rank => 5), method: :put do %>
        <% if current_user_vote(bandname) > 4 %>
          <%= render 'layouts/voteup' %>
        <% else %>
          <%= render 'layouts/votedn' %>
        <% end %>
      <% end %>

app/views/layouts/_votedn.html.erb
          <span style="font-size: 20px" class="glyphicon glyphicon-star-empty"></span>

app/views/layouts/_voteup.html.erb
          <span style="font-size: 20px" class="glyphicon glyphicon-star"></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bandnamit</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/main/home.html.erb
<h1>Welcome!</h1>

<% if !logged_in? %>
    <p>Do you have a great idea for a band name? Do you want to see other great ideas for band names? This is the place for you!
    Enter your band name ideas, vote on other band name ideas... Become a <i>Bandnamer</i>.</p>
    <p>
    <%= link_to "Log in", login_path, :class => "btn btn-primary" %> or 
    <%= link_to "Sign up", signup_path, :class => "btn btn-primary" %> to get started.
    </p> 
<% else %>
    <p><%= link_to "Enter a band name", idea_path, :class => "btn btn-primary" %></p>
    <p><%= link_to "Vote on some random band names", vote_path, :class => "btn btn-primary" %></p>
    <p>Or click on any band name to vote</p>
    </ul>
<% end %>

<h1>Top Band Names</h1>

<table class="tablemd table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Rank</th>
    </tr>
  </thead>
  <tbody>
        <%= render @bandnames %>
  </tbody>
</table>
<%= will_paginate @bandnames %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Submit changes", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

</ul>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:button_text, "Create my account") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <table>
    <tbody>
      <tr align='center'> 
        <td><%= gravatar_for @user %></td>
        <td><%= @user.name %></td>
      </tr>
    </tbody>
  </table>
</h1>
<% if @bandnames.any? %>
  <h2>Band Names (<%= @bandnames.count %>)</h2>
  <table class="tablemd table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Rank</th>
      </tr>
    </thead>
    <tbody>
          <%= render @bandnames %>
    </tbody>
  </table>
  <%= will_paginate @bandnames %>
<% end %>
<br>
<p><%= link_to "Home", root_path, :class => "btn btn-primary" %></p>

app/views/votelot/new.html.erb
<h1>Vote</h1>
<p>Vote on any or all of the following by clicking the stars.</p>
  <table class="tablemd table-striped">
    <thead>
      <tr>
        <th scope="col">Band name</th>
        <th scope="col">Your vote</th>
      </tr>
    </thead>
    <tbody>
      <% @lot.each do |b| %>
        <tr>
            <td scope="col"><%= b.name %></td>
            <td scope="col"><%= render partial: 'layouts/vote', locals: {bandname: b} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<p><%= link_to "Home", root_path, :class => "btn btn-primary" %></p>